# Generated by Django 3.0.5 on 2020-05-06 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_contact'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='CContact',
        ),
    ]
